// Private CopyrightAdaptive metadata copy of CopyrightTex_XIV.fxh.
// Source SHA-256: 5b7ecc5b112b3de0b1380c7261cf47969680ed6c10e06287f4fdfa988ed43c5a
// Generated by tools/Sync-CopyrightAdaptiveStyles.ps1 with required asset filtering.
// Legacy style IDs are retained; the compact menu uses its own preprocessor input.

/*------------------.
| :: Description :: |
'-------------------/

    Texture Header (version 0.1)

    Authors: originalnicodr, prod80, uchu suzume, Marot Satil

    About:
    Provides a variety of blending methods for you to use as you wish. Just include this header.

    History:
    (*) Feature (+) Improvement (x) Bugfix (-) Information (!) Compatibility

    Version 0.1 by Marot Satil & uchu suzume
    + Divided into corresponding lists for each game.
    * Added warning message when specified Non-existing source reference numbers.
    x Fixed incorrect specification of PSO2 logo in ui_item and Texture Definition.

*/

// -------------------------------------
// Texture Macros
// -------------------------------------

#ifndef CopyrightAdaptive_Texture_Source
#define CopyrightAdaptive_Texture_Source 0
#endif
#undef COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE
#undef COPYRIGHTADAPTIVE_UI_INDEX

// A menu choice takes precedence. Invalid menu positions use the first available style.
#if defined(CopyrightAdaptive_Menu_Source)
#if CopyrightAdaptive_Menu_Source == 0
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 0
#elif CopyrightAdaptive_Menu_Source == 1
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 1
#elif CopyrightAdaptive_Menu_Source == 2
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 2
#elif CopyrightAdaptive_Menu_Source == 3
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 3
#elif CopyrightAdaptive_Menu_Source == 4
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 4
#elif CopyrightAdaptive_Menu_Source == 5
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 5
#elif CopyrightAdaptive_Menu_Source == 6
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 6
#elif CopyrightAdaptive_Menu_Source == 7
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 7
#elif CopyrightAdaptive_Menu_Source == 8
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 8
#elif CopyrightAdaptive_Menu_Source == 9
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 9
#elif CopyrightAdaptive_Menu_Source == 10
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 10
#elif CopyrightAdaptive_Menu_Source == 11
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 11
#elif CopyrightAdaptive_Menu_Source == 12
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 12
#elif CopyrightAdaptive_Menu_Source == 13
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 13
#elif CopyrightAdaptive_Menu_Source == 14
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 14
#elif CopyrightAdaptive_Menu_Source == 15
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 17
#elif CopyrightAdaptive_Menu_Source == 16
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 18
#elif CopyrightAdaptive_Menu_Source == 17
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 19
#elif CopyrightAdaptive_Menu_Source == 18
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 20
#elif CopyrightAdaptive_Menu_Source == 19
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 21
#elif CopyrightAdaptive_Menu_Source == 20
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 22
#elif CopyrightAdaptive_Menu_Source == 21
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 23
#elif CopyrightAdaptive_Menu_Source == 22
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 24
#elif CopyrightAdaptive_Menu_Source == 23
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 25
#elif CopyrightAdaptive_Menu_Source == 24
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 26
#elif CopyrightAdaptive_Menu_Source == 25
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 27
#elif CopyrightAdaptive_Menu_Source == 26
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 28
#elif CopyrightAdaptive_Menu_Source == 27
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 29
#elif CopyrightAdaptive_Menu_Source == 28
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 30
#elif CopyrightAdaptive_Menu_Source == 29
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 31
#elif CopyrightAdaptive_Menu_Source == 30
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 32
#elif CopyrightAdaptive_Menu_Source == 31
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 33
#elif CopyrightAdaptive_Menu_Source == 32
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 34
#elif CopyrightAdaptive_Menu_Source == 33
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 35
#elif CopyrightAdaptive_Menu_Source == 34
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 36
#elif CopyrightAdaptive_Menu_Source == 35
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 37
#elif CopyrightAdaptive_Menu_Source == 36
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 38
#elif CopyrightAdaptive_Menu_Source == 37
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 39
#elif CopyrightAdaptive_Menu_Source == 38
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 40
#elif CopyrightAdaptive_Menu_Source == 39
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 41
#elif CopyrightAdaptive_Menu_Source == 40
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 42
#elif CopyrightAdaptive_Menu_Source == 41
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 43
#elif CopyrightAdaptive_Menu_Source == 42
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 44
#elif CopyrightAdaptive_Menu_Source == 43
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 45
#elif CopyrightAdaptive_Menu_Source == 44
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 46
#elif CopyrightAdaptive_Menu_Source == 45
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 47
#elif CopyrightAdaptive_Menu_Source == 46
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 48
#elif CopyrightAdaptive_Menu_Source == 47
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 49
#elif CopyrightAdaptive_Menu_Source == 48
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 50
#elif CopyrightAdaptive_Menu_Source == 49
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 51
#elif CopyrightAdaptive_Menu_Source == 50
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 52
#elif CopyrightAdaptive_Menu_Source == 51
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 53
#elif CopyrightAdaptive_Menu_Source == 52
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 54
#elif CopyrightAdaptive_Menu_Source == 53
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 55
#elif CopyrightAdaptive_Menu_Source == 54
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 56
#elif CopyrightAdaptive_Menu_Source == 55
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 57
#elif CopyrightAdaptive_Menu_Source == 56
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 58
#elif CopyrightAdaptive_Menu_Source == 57
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 59
#elif CopyrightAdaptive_Menu_Source == 58
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 60
#elif CopyrightAdaptive_Menu_Source == 59
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 61
#elif CopyrightAdaptive_Menu_Source == 60
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 62
#elif CopyrightAdaptive_Menu_Source == 61
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 63
#elif CopyrightAdaptive_Menu_Source == 62
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 64
#else
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 0
#endif
#else
// Without a menu override, the original Texture_Source style ID remains valid.
#if CopyrightAdaptive_Texture_Source == 0
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 0
#elif CopyrightAdaptive_Texture_Source == 1
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 1
#elif CopyrightAdaptive_Texture_Source == 2
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 2
#elif CopyrightAdaptive_Texture_Source == 3
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 3
#elif CopyrightAdaptive_Texture_Source == 4
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 4
#elif CopyrightAdaptive_Texture_Source == 5
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 5
#elif CopyrightAdaptive_Texture_Source == 6
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 6
#elif CopyrightAdaptive_Texture_Source == 7
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 7
#elif CopyrightAdaptive_Texture_Source == 8
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 8
#elif CopyrightAdaptive_Texture_Source == 9
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 9
#elif CopyrightAdaptive_Texture_Source == 10
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 10
#elif CopyrightAdaptive_Texture_Source == 11
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 11
#elif CopyrightAdaptive_Texture_Source == 12
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 12
#elif CopyrightAdaptive_Texture_Source == 13
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 13
#elif CopyrightAdaptive_Texture_Source == 14
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 14
#elif CopyrightAdaptive_Texture_Source == 17
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 17
#elif CopyrightAdaptive_Texture_Source == 18
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 18
#elif CopyrightAdaptive_Texture_Source == 19
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 19
#elif CopyrightAdaptive_Texture_Source == 20
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 20
#elif CopyrightAdaptive_Texture_Source == 21
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 21
#elif CopyrightAdaptive_Texture_Source == 22
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 22
#elif CopyrightAdaptive_Texture_Source == 23
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 23
#elif CopyrightAdaptive_Texture_Source == 24
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 24
#elif CopyrightAdaptive_Texture_Source == 25
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 25
#elif CopyrightAdaptive_Texture_Source == 26
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 26
#elif CopyrightAdaptive_Texture_Source == 27
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 27
#elif CopyrightAdaptive_Texture_Source == 28
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 28
#elif CopyrightAdaptive_Texture_Source == 29
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 29
#elif CopyrightAdaptive_Texture_Source == 30
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 30
#elif CopyrightAdaptive_Texture_Source == 31
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 31
#elif CopyrightAdaptive_Texture_Source == 32
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 32
#elif CopyrightAdaptive_Texture_Source == 33
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 33
#elif CopyrightAdaptive_Texture_Source == 34
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 34
#elif CopyrightAdaptive_Texture_Source == 35
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 35
#elif CopyrightAdaptive_Texture_Source == 36
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 36
#elif CopyrightAdaptive_Texture_Source == 37
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 37
#elif CopyrightAdaptive_Texture_Source == 38
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 38
#elif CopyrightAdaptive_Texture_Source == 39
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 39
#elif CopyrightAdaptive_Texture_Source == 40
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 40
#elif CopyrightAdaptive_Texture_Source == 41
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 41
#elif CopyrightAdaptive_Texture_Source == 42
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 42
#elif CopyrightAdaptive_Texture_Source == 43
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 43
#elif CopyrightAdaptive_Texture_Source == 44
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 44
#elif CopyrightAdaptive_Texture_Source == 45
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 45
#elif CopyrightAdaptive_Texture_Source == 46
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 46
#elif CopyrightAdaptive_Texture_Source == 47
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 47
#elif CopyrightAdaptive_Texture_Source == 48
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 48
#elif CopyrightAdaptive_Texture_Source == 49
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 49
#elif CopyrightAdaptive_Texture_Source == 50
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 50
#elif CopyrightAdaptive_Texture_Source == 51
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 51
#elif CopyrightAdaptive_Texture_Source == 52
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 52
#elif CopyrightAdaptive_Texture_Source == 53
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 53
#elif CopyrightAdaptive_Texture_Source == 54
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 54
#elif CopyrightAdaptive_Texture_Source == 55
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 55
#elif CopyrightAdaptive_Texture_Source == 56
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 56
#elif CopyrightAdaptive_Texture_Source == 57
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 57
#elif CopyrightAdaptive_Texture_Source == 58
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 58
#elif CopyrightAdaptive_Texture_Source == 59
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 59
#elif CopyrightAdaptive_Texture_Source == 60
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 60
#elif CopyrightAdaptive_Texture_Source == 61
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 61
#elif CopyrightAdaptive_Texture_Source == 62
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 62
#elif CopyrightAdaptive_Texture_Source == 63
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 63
#elif CopyrightAdaptive_Texture_Source == 64
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 64
#else
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 0
#endif
#endif

#if COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 0
#define COPYRIGHTADAPTIVE_UI_INDEX 0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 1
#define COPYRIGHTADAPTIVE_UI_INDEX 1
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 2
#define COPYRIGHTADAPTIVE_UI_INDEX 2
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 3
#define COPYRIGHTADAPTIVE_UI_INDEX 3
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 4
#define COPYRIGHTADAPTIVE_UI_INDEX 4
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 5
#define COPYRIGHTADAPTIVE_UI_INDEX 5
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 6
#define COPYRIGHTADAPTIVE_UI_INDEX 6
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 7
#define COPYRIGHTADAPTIVE_UI_INDEX 7
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 8
#define COPYRIGHTADAPTIVE_UI_INDEX 8
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 9
#define COPYRIGHTADAPTIVE_UI_INDEX 9
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 10
#define COPYRIGHTADAPTIVE_UI_INDEX 10
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 11
#define COPYRIGHTADAPTIVE_UI_INDEX 11
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 12
#define COPYRIGHTADAPTIVE_UI_INDEX 12
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 13
#define COPYRIGHTADAPTIVE_UI_INDEX 13
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 14
#define COPYRIGHTADAPTIVE_UI_INDEX 14
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 17
#define COPYRIGHTADAPTIVE_UI_INDEX 15
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 18
#define COPYRIGHTADAPTIVE_UI_INDEX 16
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 19
#define COPYRIGHTADAPTIVE_UI_INDEX 17
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 20
#define COPYRIGHTADAPTIVE_UI_INDEX 18
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 21
#define COPYRIGHTADAPTIVE_UI_INDEX 19
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 22
#define COPYRIGHTADAPTIVE_UI_INDEX 20
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 23
#define COPYRIGHTADAPTIVE_UI_INDEX 21
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 24
#define COPYRIGHTADAPTIVE_UI_INDEX 22
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 25
#define COPYRIGHTADAPTIVE_UI_INDEX 23
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 26
#define COPYRIGHTADAPTIVE_UI_INDEX 24
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 27
#define COPYRIGHTADAPTIVE_UI_INDEX 25
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 28
#define COPYRIGHTADAPTIVE_UI_INDEX 26
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 29
#define COPYRIGHTADAPTIVE_UI_INDEX 27
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 30
#define COPYRIGHTADAPTIVE_UI_INDEX 28
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 31
#define COPYRIGHTADAPTIVE_UI_INDEX 29
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 32
#define COPYRIGHTADAPTIVE_UI_INDEX 30
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 33
#define COPYRIGHTADAPTIVE_UI_INDEX 31
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 34
#define COPYRIGHTADAPTIVE_UI_INDEX 32
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 35
#define COPYRIGHTADAPTIVE_UI_INDEX 33
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 36
#define COPYRIGHTADAPTIVE_UI_INDEX 34
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 37
#define COPYRIGHTADAPTIVE_UI_INDEX 35
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 38
#define COPYRIGHTADAPTIVE_UI_INDEX 36
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 39
#define COPYRIGHTADAPTIVE_UI_INDEX 37
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 40
#define COPYRIGHTADAPTIVE_UI_INDEX 38
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 41
#define COPYRIGHTADAPTIVE_UI_INDEX 39
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 42
#define COPYRIGHTADAPTIVE_UI_INDEX 40
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 43
#define COPYRIGHTADAPTIVE_UI_INDEX 41
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 44
#define COPYRIGHTADAPTIVE_UI_INDEX 42
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 45
#define COPYRIGHTADAPTIVE_UI_INDEX 43
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 46
#define COPYRIGHTADAPTIVE_UI_INDEX 44
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 47
#define COPYRIGHTADAPTIVE_UI_INDEX 45
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 48
#define COPYRIGHTADAPTIVE_UI_INDEX 46
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 49
#define COPYRIGHTADAPTIVE_UI_INDEX 47
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 50
#define COPYRIGHTADAPTIVE_UI_INDEX 48
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 51
#define COPYRIGHTADAPTIVE_UI_INDEX 49
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 52
#define COPYRIGHTADAPTIVE_UI_INDEX 50
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 53
#define COPYRIGHTADAPTIVE_UI_INDEX 51
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 54
#define COPYRIGHTADAPTIVE_UI_INDEX 52
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 55
#define COPYRIGHTADAPTIVE_UI_INDEX 53
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 56
#define COPYRIGHTADAPTIVE_UI_INDEX 54
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 57
#define COPYRIGHTADAPTIVE_UI_INDEX 55
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 58
#define COPYRIGHTADAPTIVE_UI_INDEX 56
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 59
#define COPYRIGHTADAPTIVE_UI_INDEX 57
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 60
#define COPYRIGHTADAPTIVE_UI_INDEX 58
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 61
#define COPYRIGHTADAPTIVE_UI_INDEX 59
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 62
#define COPYRIGHTADAPTIVE_UI_INDEX 60
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 63
#define COPYRIGHTADAPTIVE_UI_INDEX 61
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 64
#define COPYRIGHTADAPTIVE_UI_INDEX 62
#else
// Manual-only custom images are not dropdown entries; show the first menu item.
#define COPYRIGHTADAPTIVE_UI_INDEX 0
#endif

#undef COPYRIGHTADAPTIVE_TEXTURE_COMBO
#define COPYRIGHTADAPTIVE_TEXTURE_COMBO(variable, name_label, description) \
uniform int variable \
< \
    ui_items = \
        "00- FFXIV\0" \
        "01- Nalukai\0" \
        "02- Yomi\0" \
        "03- Kabel\0" \
        "04- Neneko Fipps\0" \
        "05- Neneko Foglihten No.07\0" \
        "06- Neneko 000webfont\0" \
        "07- Neneko !Sketchy Times\0" \
        "08- Neneko Arual\0" \
        "09- Poppins\0" \
        "10- Sophia DF 4.5\0" \
        "11- Meridien\0" \
        "12- Euphoria Script\0" \
        "13- Grandmaster\0" \
        "14- Midnight Sun DF\0" \
        "-------------------------------------------------\0" \
        "18-Gill Sans\0" \
        "19-Sophia DF 4\0" \
        "20-Midnight Sun DF 2\0" \
        "21-Grandmaster 2.5\0" \
        "-------------------------------------------------\0" \
        "23- Frutiger XCn\0" \
        "24- Poppins Rectangle\0" \
        "25- Futura Large\0" \
        "26- Sophia DF Large\0" \
        "27- Sophia DF Large 2\0" \
        "28- Sophia DF\0" \
        "29- Meridien Large\0" \
        "30- Caslon Old Face\0" \
        "31- Andante\0" \
        "32- Tokyosign\0" \
        "33- Candlelight\0" \
        "34- Helvetica\0" \
        "-------------------------------------------------\0" \
        "36- Futura\0" \
        "37- Sophia DF 3\0" \
        "38- Copperplate Gothic\0" \
        "39- Grandmaster 2\0" \
        "-------------------------------------------------\0" \
        "41- Baskerville\0" \
        "42- Josefin Slab\0" \
        "43- Josefin Slab 2\0" \
        "44- Codex\0" \
        "45- Empire\0" \
        "46- Rachel DF\0" \
        "-------------------------------------------------\0" \
        "48- Futura 2\0" \
        "49- Futura Square\0" \
        "50- Sophia DF Square\0" \
        "51- Sophia DF 2\0" \
        "52- Meridian Square\0" \
        "53- Stymie Square\0" \
        "54- Stymie Square 2\0" \
        "55- Broadway Square\0" \
        "56- Grandmaster 3\0" \
        "57- Bernhard Neo DF\0" \
        "58- Super Bodoni DF\0" \
        "59- Bungee Shade\0" \
        "60- Bernhard Neo DF 2\0" \
        "61- Grandmaster 4\0" \
        "-------------------------------------------------\0" \
        "63- Gill Sans Framed\0" \
        "64- Gill Sans Framed 2\0" \
        ; \
    ui_bind = "CopyrightAdaptive_Menu_Source"; \
    ui_label = name_label; \
    ui_tooltip = description; \
    ui_spacing = 1; \
    ui_type = "combo"; \
> = COPYRIGHTADAPTIVE_UI_INDEX;

#if COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 0
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 1
#define COPYRIGHTADAPTIVE_SOURCE_FILE "CopyrightF4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1250.0, 200.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 2
#define COPYRIGHTADAPTIVE_SOURCE_FILE "CopyrightYWhH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 900.0, 150.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 3
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_geometric231(Kabel)_square.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 550.0, 500.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 4
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_neneko_fipps.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1200.0, 250.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 5
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_neneko_foglihten_no07.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1200.0, 250.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 6
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_neneko_000webfont.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1200.0, 400.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 7
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_neneko_!sketchy_times.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1200.0, 350.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 8
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_neneko_arual.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 600.0, 600.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 9
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_poppins.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 900.0, 60.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 10
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_sophia_df_4.5.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 900.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 11
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_meridien.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1200.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 12
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_euphoriascript.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1000.0, 120.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 13
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_grandmaster.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 700.0, 200.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 14
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_midnightsun_df.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 950.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 17
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 18
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_gill_sans.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 750.0, 150.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 19
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_sophia_df_4.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 750.0, 200.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 20
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_midnightsun_df_2.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 750.0, 200.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 21
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_grandmaster_2.5.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 750.0, 500.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 22
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 23
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_frutiger_xcn.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1000.0, 300.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 24
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_poppins_rectangle.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1200.0, 180.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 25
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_futura_large.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1200.0, 250.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 26
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_sophia_df_large.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1200.0, 300.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 27
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_sophia_df_large_2.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1200.0, 300.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 28
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_sophia_df.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 400.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 29
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_meridien_large.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1000.0, 300.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 30
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_caslon_old_face.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1000.0, 250.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 31
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_andante.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 900.0, 250.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 32
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_tokyosign.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1000.0, 300.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 33
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_candlelight.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 1000.0, 200.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 34
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_swiss721(Helvetica).png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 680.0, 300.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 35
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 36
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_futura.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 750.0, 250.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 37
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_sophia_df_3.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 600.0, 200.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 38
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_copperplate.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 750.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 39
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_grandmaster_2.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 700.0, 500.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 40
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 41
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_baskerville.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 830.0, 300.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 42
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_josefin_slab.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 700.0, 350.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 43
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_josefin_slab_2.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 700.0, 350.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 44
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_codex.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 900.0, 300.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 45
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_empire.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 350.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 46
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_rachel_df.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 900.0, 550.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 47
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 48
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_futura_2.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 400.0, 300.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 49
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_futura_square.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 400.0, 400.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 50
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_sophia_df_square.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 400.0, 400.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 51
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_sophia_df_2.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 600.0, 400.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 52
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_meridien_square.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 500.0, 500.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 53
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_stymie_square.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 400.0, 400.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 54
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_stymie_square_2.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 500.0, 500.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 55
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_broadway.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 500.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 56
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_grandmaster_3.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 500.0, 700.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 57
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_bernhard_neo_df.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 600.0, 500.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 58
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_super_bodoni_df.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 750.0, 500.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 59
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_bungee_shade.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 600.0, 300.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 60
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_bernhard_neo_df_2.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 400.0, 700.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 61
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_grandmaster_4.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 250.0, 1200.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 62
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 63
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_gill_sans_nova_framed.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 600.0, 300.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 64
#define COPYRIGHTADAPTIVE_SOURCE_FILE "copyright_ffxiv_gill_sans_nova_framed_2.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 500.0, 500.0
#else
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#endif
