// Private CopyrightAdaptive metadata copy of CopyrightTex_Custom.fxh.
// Source SHA-256: 55365cb9850268c7dec4863ac1ac255ce1a617040fe7ff9e12656befe7dbb031
// Generated by tools/Sync-CopyrightAdaptiveStyles.ps1 with required asset filtering.
// Legacy style IDs are retained; the compact menu uses its own preprocessor input.

/*------------------.
| :: Description :: |
'-------------------/

    Texture Header (version 0.1)

    Authors: originalnicodr, prod80, uchu suzume, Marot Satil

    About:
    Provides a variety of blending methods for you to use as you wish. Just include this header.

    History:
    (*) Feature (+) Improvement (x) Bugfix (-) Information (!) Compatibility

    Version 0.1 by Marot Satil & uchu suzume
    + Divided into corresponding lists for each game.
    * Added warning message when specified Non-existing source reference numbers.
    x Fixed incorrect specification of PSO2 logo in ui_item and Texture Definition.

*/

// -------------------------------------
// Texture Macros
// -------------------------------------

#ifndef CopyrightAdaptive_Texture_Source
#define CopyrightAdaptive_Texture_Source 0
#endif
#undef COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE
#undef COPYRIGHTADAPTIVE_UI_INDEX

// A menu choice takes precedence. Invalid menu positions use the first available style.
#if defined(CopyrightAdaptive_Menu_Source)
#if CopyrightAdaptive_Menu_Source == 0
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 0
#elif CopyrightAdaptive_Menu_Source == 1
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 1
#elif CopyrightAdaptive_Menu_Source == 2
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 2
#elif CopyrightAdaptive_Menu_Source == 3
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 3
#elif CopyrightAdaptive_Menu_Source == 4
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 4
#elif CopyrightAdaptive_Menu_Source == 5
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 5
#elif CopyrightAdaptive_Menu_Source == 6
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 6
#elif CopyrightAdaptive_Menu_Source == 7
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 7
#elif CopyrightAdaptive_Menu_Source == 8
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 8
#elif CopyrightAdaptive_Menu_Source == 9
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 9
#elif CopyrightAdaptive_Menu_Source == 10
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 10
#elif CopyrightAdaptive_Menu_Source == 11
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 11
#else
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 0
#endif
#else
// Without a menu override, the original Texture_Source style ID remains valid.
#if CopyrightAdaptive_Texture_Source == 0
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 0
#elif CopyrightAdaptive_Texture_Source == 1
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 1
#elif CopyrightAdaptive_Texture_Source == 2
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 2
#elif CopyrightAdaptive_Texture_Source == 3
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 3
#elif CopyrightAdaptive_Texture_Source == 4
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 4
#elif CopyrightAdaptive_Texture_Source == 5
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 5
#elif CopyrightAdaptive_Texture_Source == 6
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 6
#elif CopyrightAdaptive_Texture_Source == 7
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 7
#elif CopyrightAdaptive_Texture_Source == 8
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 8
#elif CopyrightAdaptive_Texture_Source == 9
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 9
#elif CopyrightAdaptive_Texture_Source == 10
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 10
#elif CopyrightAdaptive_Texture_Source == 11
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 11
#else
#define COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE 0
#endif
#endif

#if COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 0
#define COPYRIGHTADAPTIVE_UI_INDEX 0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 1
#define COPYRIGHTADAPTIVE_UI_INDEX 1
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 2
#define COPYRIGHTADAPTIVE_UI_INDEX 2
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 3
#define COPYRIGHTADAPTIVE_UI_INDEX 3
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 4
#define COPYRIGHTADAPTIVE_UI_INDEX 4
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 5
#define COPYRIGHTADAPTIVE_UI_INDEX 5
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 6
#define COPYRIGHTADAPTIVE_UI_INDEX 6
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 7
#define COPYRIGHTADAPTIVE_UI_INDEX 7
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 8
#define COPYRIGHTADAPTIVE_UI_INDEX 8
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 9
#define COPYRIGHTADAPTIVE_UI_INDEX 9
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 10
#define COPYRIGHTADAPTIVE_UI_INDEX 10
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 11
#define COPYRIGHTADAPTIVE_UI_INDEX 11
#else
// Manual-only custom images are not dropdown entries; show the first menu item.
#define COPYRIGHTADAPTIVE_UI_INDEX 0
#endif

#undef COPYRIGHTADAPTIVE_TEXTURE_COMBO
#define COPYRIGHTADAPTIVE_TEXTURE_COMBO(variable, name_label, description) \
uniform int variable \
< \
    ui_items = \
        "Logo 00\0" \
        "Logo 01\0" \
        "Logo 02\0" \
        "Logo 03\0" \
        "Logo 04\0" \
        "Logo 05\0" \
        "Logo 06\0" \
        "Logo 07\0" \
        "Logo 08\0" \
        "Logo 09\0" \
        "Logo 10\0" \
        "-------------------------------------------------\0" \
        ; \
    ui_bind = "CopyrightAdaptive_Menu_Source"; \
    ui_label = name_label; \
    ui_tooltip = description; \
    ui_spacing = 1; \
    ui_type = "combo"; \
> = COPYRIGHTADAPTIVE_UI_INDEX;

#if COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 0
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 1
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 2
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 3
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 4
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 5
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 6
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 7
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 8
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 9
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 10
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#elif COPYRIGHTADAPTIVE_EFFECTIVE_SOURCE == 11
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#else
#define COPYRIGHTADAPTIVE_SOURCE_FILE "Copyright4kH.png"
#define COPYRIGHTADAPTIVE_SOURCE_SIZE 800.0, 100.0
#endif
